# テンソル

In [2]:
%matplotlib inline

In [3]:
import torch
import numpy as np

In [ ]:
#データから直接テンソルに変換
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)
print(x_data.dtype) #要素の型は引き継がれる
                    #typeはそのオブジェクトのクラス（型）、dtypeは要素の型

tensor([[1, 2],
        [3, 4]])
torch.int64


In [5]:
#NumPy arrayからテンソルに変換
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(np_array)
print(x_np)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


In [ ]:
#他のテンソルから作成
x_ones = torch.ones_like(x_data) #_likeがつく場合、引数のテンソルと同じ shape / dtype / device を自動的に引き継ぐ
print(x_ones)
print(type(x_ones))
print(x_ones.dtype)

x_rand = torch.rand_like(x_data, dtype=torch.float) #datatypeを上書き更新
print(x_rand)

tensor([[1, 1],
        [1, 1]])
<class 'torch.Tensor'>
torch.int64
tensor([[0.4407, 0.1108],
        [0.4454, 0.9899]])


In [ ]:
#ランダム値や定数のテンソルの作成
shape = (2,3,) #2行(0次元)3列(1次元)
rand_tensor = torch.rand(shape) #_likeがつかない場合、形状（shape）を明示的に指定する必要がある
ones_tensor = torch.ones(shape) #dtype や device はデフォルト（float32, CPU）
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.5795, 0.1200, 0.9293],
        [0.6363, 0.4083, 0.4882]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
#テンソルの属性変数
#テンソルは属性変数として、その形状、データの型、保存されているデバイスを保持している
tensor_data = torch.rand(3,4)

print(tensor_data.shape)
print(tensor_data.dtype)
print(tensor_data.device)

torch.Size([3, 4])
torch.float32
cpu


In [24]:
#テンソルの操作

# GPUが使用可能であれば、GPU上にテンソルを移動させる
if torch.cuda.is_available():
    tensor = tensor_data.to("cuda") #cpuメモリからgpuメモリにデータをコピーしたテンソルを返す
                                    #変数名を同じにしてもいいが上書きされる

#numpy-likeなindexingとslicing
tensor = torch.rand(4,4)
print(f"tensor:\n{tensor}") 
print("First row:",tensor[0]) #[0,:]の:は省略可
print("First column:",tensor[:,0]) #rowは行、columnは列
print("Last column:",tensor[...,-1])
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

tensor:
tensor([[0.0133, 0.3114, 0.8070, 0.4081],
        [0.8725, 0.5603, 0.2896, 0.4620],
        [0.5949, 0.5586, 0.6468, 0.7503],
        [0.9125, 0.0163, 0.7459, 0.5125]])
First row: tensor([0.0133, 0.3114, 0.8070, 0.4081])
First column: tensor([0.0133, 0.8725, 0.5949, 0.9125])
Last column: tensor([0.4081, 0.4620, 0.7503, 0.5125])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
#テンソルの結合 
t1 = torch.cat([tensor, tensor, tensor], dim=0) #行方向
t2 = torch.cat([tensor, tensor, tensor], dim=1) #列方向
print(t1)
print(t2)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [33]:
#算術演算

#テンソル行列の掛け算
y1 = tensor @ tensor.T #@はPythonの行列積演算子
y2 = tensor.matmul(tensor.T) #matmulはPyTorchの行列積メソッド
                             #mat → matrix（行列）、mul → multiply（掛け算する）
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3) #out=は「計算結果を格納する既存のテンソルを指定する」
                                       #既に確保してあるメモリ領域に結果を書き込むので、節約

print("tenosr:\n",tensor)
print("tenosrの転置行列:\n",tensor.T)
print("\n", y1,"\n", y2,"\n", y3)

#要素ごとの積
z1 = tensor*tensor.T
z2 = tensor.mul(tensor.T)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor.T, out=z3)

print("\n", z1,"\n", z2,"\n", z3)

tenosr:
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tenosrの転置行列:
 tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

 tensor([[1., 0., 1., 1.],
        [0., 0., 0., 0.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 
 tensor([[1., 0., 1., 1.],
        [0., 0., 0., 0.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 
 tensor([[1., 0., 1., 1.],
        [0., 0., 0., 0.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
#1要素のテンソル
agg = tensor.sum()
agg_item = agg.item() #.item()でPythonの数値型変数に変換
print(type(tensor))
print(agg_item, type(agg_item))

<class 'torch.Tensor'>
12.0 <class 'float'>


In [ ]:
#インプレース(演算結果をオペランドに格納する演算)操作
#オペランドとは、演算の対象となる値や変数（演算子はoperator）
print(tensor, "\n")
tensor.add_(5) #_がつき、xの内容そのものを更新（x.copy_(y)等）
print(tensor, "\n")

tensor2 = tensor.add(5) #新しいテンソルを返すので変数を用意
print(tensor2)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]]) 

tensor([[16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.]])


In [ ]:
#NumPyとの変換
#CPU上のテンソルとNumpy arraysは同じメモリを共有することができ、相互変換が容易

#Tensor to NumPy array
t = torch.ones(5)
n = t.numpy() #PyTorchのTensorクラスが持っているメソッド
print(f"t: {t,}")
print(f"n: {n}")

t.add_(5) #テンソルが変化するとNumpy側も変化する
print(f"t: {t}")
print(f"n: {n}")

#NumPy array to Tensor
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n) #numpyではnp.add_(5)はできない
print(f"t: {t}") #numpyのデフォルトはfloat64だからそれが引き継がれる
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([6., 6., 6., 6., 6.])
n: [6. 6. 6. 6. 6.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
