In [1]:
import torch
print(torch.cuda.is_available())

False


In [2]:
import torch.nn as nn

In [3]:
#3ノード →　2ノードの全結合層(fully-connected layer)
fc = nn.Linear(3, 2)

In [4]:
fc

Linear(in_features=3, out_features=2, bias=True)

In [5]:
fc.weight

Parameter containing:
tensor([[-0.4265, -0.4057,  0.0606],
        [ 0.2648, -0.3604,  0.5520]], requires_grad=True)

In [6]:
fc.bias

Parameter containing:
tensor([0.3587, 0.4347], requires_grad=True)

In [7]:
#乱数のシードを固定
torch.manual_seed(0)

In [8]:
fc = nn.Linear(3, 2)

In [9]:
fc.weight

Parameter containing:
tensor([[-0.0043,  0.3097, -0.4752],
        [-0.4249, -0.2224,  0.1548]], requires_grad=True)

In [10]:
fc.bias

Parameter containing:
tensor([-0.0114,  0.4578], requires_grad=True)

線形変換
・データをテンソル型に変える

In [11]:
x = torch.tensor([[1., 2., 3.]])

In [12]:
type(x), x.dtype

(torch.Tensor, torch.float32)

In [13]:
u = fc(x)

In [14]:
u

tensor([[-0.8219,  0.0526]], grad_fn=<AddmmBackward0>)

In [15]:
#非線形変換の計算
import torch.nn.functional as F

In [16]:
#ReLU関数
h = F.relu(u)

In [17]:
h

tensor([[0.0000, 0.0526]], grad_fn=<ReluBackward0>)

In [18]:
#目的関数
#目標値
t = torch.tensor([[1.], [3.]])

In [19]:
#予測値
y = torch.tensor([[2.], [4.]])

In [20]:
#平均二乗誤差
F.mse_loss(y, t)

tensor(1.)